version: "3.4"

services:
  api:
    container_name: xendit_marvels_comics_api
    image: xendit-marvels-comic-api
    depends_on:
      - redis
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    environment:
      NODE_ENV: development
    env_file:
      - ./.env
    ports:
      - 3000:3000
    networks:
      - internal
      - private
    volumes:
      - .:/srv/app:rw

  redis:
    container_name: xendit_marvels_comics_api_cache
    image: redis:latest
    networks:
      - private
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/data:/redis:rw

networks:
  internal:
    external: false
  private:
    external: true
